import type { TemplateItem } from '@/types/editor';
import { v4 as uuidv4 } from 'uuid';

export const TEMPLATES: TemplateItem[] = [
  // ==================== 电力行业模板（新文档核心演示场景） ====================
  {
    id: 'tpl-power-monitor',
    name: '电力全域运维监控大屏',
    industry: '电力',
    style: '深色科技风',
    thumbnail: '',
    components: [
      // 顶部标题
      { id: uuidv4(), type: 'title_text', name: '电力运维大数据监控大屏', position: { x: 500, y: 10 }, size: { width: 920, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      // ── 左侧看板：运维分析组件 ──
      { id: uuidv4(), type: 'line_chart', name: '全网电力负荷趋势', position: { x: 20, y: 75 }, size: { width: 930, height: 380 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '各站点供电量对比', position: { x: 20, y: 470 }, size: { width: 930, height: 380 }, props: {}, zIndex: 2, locked: false, visible: true },
      // ── 右侧看板：核心指标与告警 ──
      { id: uuidv4(), type: 'kpi_card', name: '实时总负荷', position: { x: 970, y: 75 }, size: { width: 300, height: 130 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '最大峰值', position: { x: 1290, y: 75 }, size: { width: 300, height: 130 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '供电总量', position: { x: 1610, y: 75 }, size: { width: 290, height: 130 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '线路完好率', position: { x: 970, y: 220 }, size: { width: 300, height: 130 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '异常告警数', position: { x: 1290, y: 220 }, size: { width: 300, height: 130 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'ranking_list', name: '故障预警列表', position: { x: 970, y: 370 }, size: { width: 930, height: 480 }, props: {}, zIndex: 8, locked: false, visible: true },
      // 左右看板分割装饰
      { id: uuidv4(), type: 'border_decoration', name: '看板分割线', position: { x: 955, y: 75 }, size: { width: 10, height: 800 }, props: {}, zIndex: 9, locked: true, visible: true },
    ],
  },
  {
    id: 'tpl-power-energy',
    name: '电网能耗数据总览大屏',
    industry: '电力',
    style: '深色科技风',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '电网能耗数据总览', position: { x: 500, y: 10 }, size: { width: 920, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      // ── 左侧看板：核心指标卡片组 ──
      { id: uuidv4(), type: 'kpi_card', name: '全网总能耗', position: { x: 20, y: 75 }, size: { width: 450, height: 150 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '今日用电量', position: { x: 20, y: 240 }, size: { width: 450, height: 150 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '节能完成率', position: { x: 20, y: 405 }, size: { width: 450, height: 150 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'number_flip', name: '碳排放指标', position: { x: 20, y: 570 }, size: { width: 450, height: 120 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'progress_bar', name: '年度节能进度', position: { x: 20, y: 710 }, size: { width: 450, height: 40 }, props: {}, zIndex: 5, locked: false, visible: true },
      // ── 右侧看板：多维度能耗趋势 ──
      { id: uuidv4(), type: 'line_chart', name: '站点能耗趋势对比', position: { x: 495, y: 75 }, size: { width: 660, height: 340 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '各区域用电统计', position: { x: 495, y: 430 }, size: { width: 660, height: 340 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'table_view', name: '站点能耗明细表', position: { x: 1170, y: 75 }, size: { width: 730, height: 695 }, props: {}, zIndex: 8, locked: false, visible: true },
    ],
  },
  {
    id: 'tpl-power-alert',
    name: '电力负荷监测预警大屏',
    industry: '电力',
    style: '深色科技风',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '电力负荷监测预警中心', position: { x: 500, y: 10 }, size: { width: 920, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      // ── 左侧看板：趋势数据分析 ──
      { id: uuidv4(), type: 'line_chart', name: '实时负荷曲线', position: { x: 20, y: 75 }, size: { width: 940, height: 350 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'area_chart', name: '负荷预测趋势', position: { x: 20, y: 440 }, size: { width: 940, height: 350 }, props: {}, zIndex: 2, locked: false, visible: true },
      // ── 右侧看板：告警信息汇总 ──
      { id: uuidv4(), type: 'gauge_chart', name: '当前负荷率', position: { x: 980, y: 75 }, size: { width: 300, height: 220 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'gauge_chart', name: '线路安全指数', position: { x: 1300, y: 75 }, size: { width: 300, height: 220 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '过载线路数', position: { x: 1620, y: 75 }, size: { width: 280, height: 220 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'ranking_list', name: '告警信息汇总', position: { x: 980, y: 310 }, size: { width: 920, height: 480 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'border_decoration', name: '看板分割线', position: { x: 965, y: 75 }, size: { width: 10, height: 750 }, props: {}, zIndex: 7, locked: true, visible: true },
    ],
  },

  // ==================== 政务/智慧城市行业模板 ====================
  {
    id: 'tpl-gov-monitor',
    name: '政务全域监控标准大屏',
    industry: '政务',
    style: '科技蓝',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '城市政务大数据监控大屏', position: { x: 300, y: 10 }, size: { width: 600, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '办理总量', position: { x: 20, y: 70 }, size: { width: 220, height: 130 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '办结率', position: { x: 260, y: 70 }, size: { width: 220, height: 130 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '待办数量', position: { x: 500, y: 70 }, size: { width: 220, height: 130 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '好评率', position: { x: 740, y: 70 }, size: { width: 220, height: 130 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'map_chart', name: '城市地图', position: { x: 260, y: 220 }, size: { width: 460, height: 380 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'line_chart', name: '人口趋势', position: { x: 20, y: 220 }, size: { width: 220, height: 380 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '政务办理统计', position: { x: 740, y: 220 }, size: { width: 220, height: 380 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'ranking_list', name: '区域排名', position: { x: 20, y: 620 }, size: { width: 300, height: 280 }, props: {}, zIndex: 8, locked: false, visible: true },
      { id: uuidv4(), type: 'pie_chart', name: '政务分类占比', position: { x: 660, y: 620 }, size: { width: 300, height: 280 }, props: {}, zIndex: 9, locked: false, visible: true },
    ],
  },
  {
    id: 'tpl-smart-city-ov',
    name: '智慧城市数据总览大屏',
    industry: '智慧城市',
    style: '政企庄重',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '智慧城市数据总览', position: { x: 300, y: 10 }, size: { width: 600, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      { id: uuidv4(), type: 'map_chart', name: '城市全域地图', position: { x: 20, y: 70 }, size: { width: 560, height: 450 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '人口总量', position: { x: 600, y: 70 }, size: { width: 190, height: 100 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: 'GDP总量', position: { x: 600, y: 180 }, size: { width: 190, height: 100 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '交通指数', position: { x: 600, y: 290 }, size: { width: 190, height: 100 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '环境质量', position: { x: 600, y: 400 }, size: { width: 190, height: 100 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'ranking_list', name: '实时预警列表', position: { x: 810, y: 70 }, size: { width: 170, height: 450 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '各区GDP对比', position: { x: 20, y: 540 }, size: { width: 370, height: 340 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'line_chart', name: '人口趋势分析', position: { x: 410, y: 540 }, size: { width: 370, height: 340 }, props: {}, zIndex: 8, locked: false, visible: true },
      { id: uuidv4(), type: 'pie_chart', name: '产业占比', position: { x: 800, y: 540 }, size: { width: 180, height: 340 }, props: {}, zIndex: 9, locked: false, visible: true },
    ],
  },
  {
    id: 'tpl-gov-indicators',
    name: '政务指标监测大屏',
    industry: '政务',
    style: '暗黑科技',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '政务核心指标监测', position: { x: 300, y: 10 }, size: { width: 600, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      { id: uuidv4(), type: 'number_flip', name: '当月办理量', position: { x: 20, y: 70 }, size: { width: 230, height: 100 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'number_flip', name: '办结率', position: { x: 270, y: 70 }, size: { width: 230, height: 100 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'number_flip', name: '满意度', position: { x: 520, y: 70 }, size: { width: 230, height: 100 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'number_flip', name: '预警事项', position: { x: 770, y: 70 }, size: { width: 230, height: 100 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '各部门政务办理量', position: { x: 20, y: 190 }, size: { width: 500, height: 300 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'line_chart', name: '月度趋势分析', position: { x: 540, y: 190 }, size: { width: 460, height: 300 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'ranking_list', name: '预警事项列表', position: { x: 20, y: 510 }, size: { width: 340, height: 320 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '重点督办', position: { x: 380, y: 510 }, size: { width: 310, height: 140 }, props: {}, zIndex: 8, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '超时预警', position: { x: 710, y: 510 }, size: { width: 270, height: 140 }, props: {}, zIndex: 9, locked: false, visible: true },
      { id: uuidv4(), type: 'progress_bar', name: '目标完成进度', position: { x: 380, y: 670 }, size: { width: 600, height: 40 }, props: {}, zIndex: 10, locked: false, visible: true },
    ],
  },
  // ==================== 安防行业模板 ====================
  {
    id: 'tpl-security-center',
    name: '安防监控指挥大屏',
    industry: '安防',
    style: '暗黑科技',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '安防监控指挥中心', position: { x: 300, y: 10 }, size: { width: 600, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '告警总数', position: { x: 20, y: 70 }, size: { width: 180, height: 120 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '已处置', position: { x: 210, y: 70 }, size: { width: 180, height: 120 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '处置率', position: { x: 400, y: 70 }, size: { width: 180, height: 120 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '在线设备', position: { x: 800, y: 70 }, size: { width: 180, height: 120 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'map_chart', name: '安防态势地图', position: { x: 210, y: 210 }, size: { width: 560, height: 420 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'ranking_list', name: '实时告警列表', position: { x: 20, y: 210 }, size: { width: 170, height: 420 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'line_chart', name: '告警趋势分析', position: { x: 790, y: 210 }, size: { width: 190, height: 200 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '事件类型分布', position: { x: 790, y: 430 }, size: { width: 190, height: 200 }, props: {}, zIndex: 8, locked: false, visible: true },
      { id: uuidv4(), type: 'ranking_list', name: '辖区排名', position: { x: 20, y: 650 }, size: { width: 480, height: 250 }, props: {}, zIndex: 9, locked: false, visible: true },
      { id: uuidv4(), type: 'table_view', name: '设备状态表', position: { x: 520, y: 650 }, size: { width: 460, height: 250 }, props: {}, zIndex: 10, locked: false, visible: true },
    ],
  },
  // ==================== 物流行业模板 ====================
  {
    id: 'tpl-logistics-dashboard',
    name: '物流调度数据大屏',
    industry: '物流',
    style: '科技蓝',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '智慧物流调度中心', position: { x: 300, y: 10 }, size: { width: 600, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '当日运单', position: { x: 20, y: 70 }, size: { width: 230, height: 120 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '在途车辆', position: { x: 270, y: 70 }, size: { width: 230, height: 120 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '准时率', position: { x: 520, y: 70 }, size: { width: 230, height: 120 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '异常运单', position: { x: 770, y: 70 }, size: { width: 230, height: 120 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'map_chart', name: '物流轨迹地图', position: { x: 270, y: 210 }, size: { width: 480, height: 380 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'line_chart', name: '运力趋势', position: { x: 20, y: 210 }, size: { width: 230, height: 380 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '区域对比', position: { x: 770, y: 210 }, size: { width: 230, height: 380 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'pie_chart', name: '路线效率', position: { x: 20, y: 610 }, size: { width: 310, height: 290 }, props: {}, zIndex: 8, locked: false, visible: true },
      { id: uuidv4(), type: 'table_view', name: '车辆状态', position: { x: 350, y: 610 }, size: { width: 630, height: 290 }, props: {}, zIndex: 9, locked: false, visible: true },
    ],
  },
  // ==================== 文旅行业模板 ====================
  {
    id: 'tpl-cultural-travel',
    name: '文旅综合展示大屏',
    industry: '文旅',
    style: '清新亮色',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '文旅综合数据大屏', position: { x: 300, y: 10 }, size: { width: 600, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '游客总量', position: { x: 20, y: 70 }, size: { width: 230, height: 120 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '今日入园', position: { x: 270, y: 70 }, size: { width: 230, height: 120 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '景区收入', position: { x: 520, y: 70 }, size: { width: 230, height: 120 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '好评率', position: { x: 770, y: 70 }, size: { width: 230, height: 120 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'map_chart', name: '景区热力图', position: { x: 270, y: 210 }, size: { width: 480, height: 380 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'line_chart', name: '游客趋势', position: { x: 20, y: 210 }, size: { width: 230, height: 380 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '景点热度', position: { x: 770, y: 210 }, size: { width: 230, height: 380 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'ring_chart', name: '收入构成', position: { x: 20, y: 610 }, size: { width: 310, height: 290 }, props: {}, zIndex: 8, locked: false, visible: true },
      { id: uuidv4(), type: 'ranking_list', name: '客流排名', position: { x: 350, y: 610 }, size: { width: 630, height: 290 }, props: {}, zIndex: 9, locked: false, visible: true },
    ],
  },
  // ==================== 原有模板（保留兼容） ====================
  {
    id: 'tpl-smart-city',
    name: '智慧城市驾驶舱',
    industry: '智慧城市',
    style: '科技感',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '标题', position: { x: 400, y: 20 }, size: { width: 400, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '人口总量', position: { x: 20, y: 80 }, size: { width: 220, height: 130 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: 'GDP总量', position: { x: 260, y: 80 }, size: { width: 220, height: 130 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '交通指数', position: { x: 500, y: 80 }, size: { width: 220, height: 130 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '空气质量', position: { x: 740, y: 80 }, size: { width: 220, height: 130 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'map_chart', name: '城市地图', position: { x: 260, y: 230 }, size: { width: 460, height: 350 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '各区GDP', position: { x: 20, y: 230 }, size: { width: 220, height: 350 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'line_chart', name: '人口趋势', position: { x: 740, y: 230 }, size: { width: 220, height: 350 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'ranking_list', name: '区域排名', position: { x: 20, y: 600 }, size: { width: 300, height: 280 }, props: {}, zIndex: 8, locked: false, visible: true },
      { id: uuidv4(), type: 'pie_chart', name: '产业占比', position: { x: 660, y: 600 }, size: { width: 300, height: 280 }, props: {}, zIndex: 9, locked: false, visible: true },
    ],
  },
  {
    id: 'tpl-sales-dashboard',
    name: '销售业绩驾驶舱',
    industry: '零售',
    style: '商务风',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '标题', position: { x: 350, y: 20 }, size: { width: 400, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '总销售额', position: { x: 20, y: 80 }, size: { width: 230, height: 130 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '订单量', position: { x: 270, y: 80 }, size: { width: 230, height: 130 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '客单价', position: { x: 520, y: 80 }, size: { width: 230, height: 130 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '毛利率', position: { x: 770, y: 80 }, size: { width: 230, height: 130 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'line_chart', name: '销售趋势', position: { x: 20, y: 230 }, size: { width: 500, height: 300 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '产品线对比', position: { x: 540, y: 230 }, size: { width: 460, height: 300 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'pie_chart', name: '区域占比', position: { x: 20, y: 550 }, size: { width: 300, height: 300 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'ranking_list', name: '销售排行', position: { x: 340, y: 550 }, size: { width: 320, height: 300 }, props: {}, zIndex: 8, locked: false, visible: true },
      { id: uuidv4(), type: 'funnel_chart', name: '转化漏斗', position: { x: 680, y: 550 }, size: { width: 320, height: 300 }, props: {}, zIndex: 9, locked: false, visible: true },
    ],
  },
  {
    id: 'tpl-production-monitor',
    name: '生产监控大屏',
    industry: '制造业',
    style: '工业风',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '标题', position: { x: 350, y: 20 }, size: { width: 400, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      { id: uuidv4(), type: 'gauge_chart', name: '设备OEE', position: { x: 20, y: 80 }, size: { width: 240, height: 200 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'gauge_chart', name: '良品率', position: { x: 280, y: 80 }, size: { width: 240, height: 200 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '日产量', position: { x: 540, y: 80 }, size: { width: 220, height: 130 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'kpi_card', name: '能耗', position: { x: 780, y: 80 }, size: { width: 220, height: 130 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'area_chart', name: '产量趋势', position: { x: 20, y: 300 }, size: { width: 500, height: 280 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '产线对比', position: { x: 540, y: 230 }, size: { width: 460, height: 350 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'radar_chart', name: '质量评估', position: { x: 20, y: 600 }, size: { width: 300, height: 300 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'table_view', name: '设备状态', position: { x: 340, y: 600 }, size: { width: 660, height: 280 }, props: {}, zIndex: 8, locked: false, visible: true },
    ],
  },
  {
    id: 'tpl-finance-overview',
    name: '财务经营概览',
    industry: '金融',
    style: '商务风',
    thumbnail: '',
    components: [
      { id: uuidv4(), type: 'title_text', name: '标题', position: { x: 350, y: 20 }, size: { width: 400, height: 50 }, props: {}, zIndex: 0, locked: false, visible: true },
      { id: uuidv4(), type: 'number_flip', name: '营收总额', position: { x: 20, y: 80 }, size: { width: 230, height: 100 }, props: {}, zIndex: 1, locked: false, visible: true },
      { id: uuidv4(), type: 'number_flip', name: '净利润', position: { x: 270, y: 80 }, size: { width: 230, height: 100 }, props: {}, zIndex: 2, locked: false, visible: true },
      { id: uuidv4(), type: 'number_flip', name: '总资产', position: { x: 520, y: 80 }, size: { width: 230, height: 100 }, props: {}, zIndex: 3, locked: false, visible: true },
      { id: uuidv4(), type: 'number_flip', name: 'ROE', position: { x: 770, y: 80 }, size: { width: 230, height: 100 }, props: {}, zIndex: 4, locked: false, visible: true },
      { id: uuidv4(), type: 'line_chart', name: '营收趋势', position: { x: 20, y: 200 }, size: { width: 480, height: 300 }, props: {}, zIndex: 5, locked: false, visible: true },
      { id: uuidv4(), type: 'bar_chart', name: '费用结构', position: { x: 520, y: 200 }, size: { width: 480, height: 300 }, props: {}, zIndex: 6, locked: false, visible: true },
      { id: uuidv4(), type: 'ring_chart', name: '收入构成', position: { x: 20, y: 520 }, size: { width: 300, height: 300 }, props: {}, zIndex: 7, locked: false, visible: true },
      { id: uuidv4(), type: 'radar_chart', name: '经营评分', position: { x: 340, y: 520 }, size: { width: 300, height: 300 }, props: {}, zIndex: 8, locked: false, visible: true },
      { id: uuidv4(), type: 'progress_bar', name: '预算执行', position: { x: 660, y: 520 }, size: { width: 340, height: 40 }, props: {}, zIndex: 9, locked: false, visible: true },
    ],
  },
];
